#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MovieCatalogMobile.Resource", IsApplication=true)]

namespace MovieCatalogMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ActionClicker_1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int btnCatalogDetails = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int btnMainCollection = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int btnMainSearch = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btnMainSettings = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int btnSearchGo = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int btnSettingsDelete = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int btnSettingsLoad = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int btnSettingsLoginSync = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int etSearchInput = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int lvMovies = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int lvSearchMovies = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int txtCatalogName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtCatalogOnlineRate = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int txtCatalogUserRate = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int txtCatalogYear = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int txtMainDisplay = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int txtRowTitle = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int txtRowYear = 2131034123;
			
			// aapt resource value: 0x7f050013
			public const int txtSettingsPassword = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int txtSettingsUser = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int catalogactivitylayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int searchactivitylayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int settingsactivitylayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
